name = "TulipaEnergyModel"
uuid = "5d7bd171-d18e-45a5-9111-f1f11ac5d04d"
authors = ["Diego A. Tejada-Arango <diego.tejadaarango@tno.nl>", "Germán Morales-España <german.morales@tno.nl>", "Lauren Clisby <lauren.clisby@tno.nl>", "Ni Wang <ni.wang@tno.nl>", "Abel Soares Siqueira <abel.s.siqueira@gmail.com>", "Suvayu Ali <s.ali@esciencecenter.nl>", "Laurent Soucasse <l.soucasse@esciencecenter.nl>", "Greg Neustroev <G.Neustroev@tudelft.nl>"]
version = "0.5.2"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
GraphMakie = "1ecd5474-83a3-4783-bb4f-06765db800d2"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
HiGHS = "87dc4568-4c63-4d18-b0c0-bb2238e4078b"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"
MetaGraphsNext = "fa8bd995-216d-47f1-8a91-f3b68fbeb377"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"
TimerOutputs = "a759f4b9-e2f1-59dc-863e-4aeb61b1ea8f"

[compat]
CSV = "0.10"
CairoMakie = "0.11"
Colors = "0.12, 0.13"
DataFrames = "1"
GraphMakie = "0.5"
Graphs = "1.8"
HiGHS = "1"
JuMP = "1"
MathOptInterface = "1"
MetaGraphsNext = "0.6, 0.7"
Plots = "1"
SparseArrays = "1"
TOML = "1"
TimerOutputs = "0.5"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
